<?php
/**
 * @var Devall\Company\Block\Account\CompanyData $block
 */
$companies = $block->getCompaniesCollection();
$currentCompany = $block->getCompany();
?>
<form method="post" action="<?= $block->escapeUrl($block->getAction()) ?>">
    <?= $block->getBlockHtml('formkey') ?>
    <select name="company" id="company">
        <?php foreach ($companies as $company): ?>
            <option
                value="<?= $company->getId() ?>"
                <?php if($company->getId() === $block->getCustomerCompanyId()): ?> selected <?php endif ?>
            >
                <?= $company->getName() ?>
            </option>
        <?php endforeach; ?>
    </select>
    <br>
    <br>
    <div class="primary">
        <button type="submit"
                class="action save primary"
                title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
            <span><?= $block->escapeHtml(__('Save')) ?></span>
        </button>
    </div>
</form>

<div id="details" data-bind="scope: 'company-details'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "#details": {
        "Magento_Ui/js/core/app": {
            "components": {
                "company-details": {
                    "component": "Devall_Company/js/company-details",
                    "config" : {
                         "country" : "<?php if($currentCompany) :?> <?=$currentCompany->getCountry()?> <?php endif ?>",
                         "street" : "<?php if($currentCompany) :?> <?=$currentCompany->getStreet()?> <?php endif ?>",
                         "streetNumber" : "<?php if($currentCompany) :?> <?=$currentCompany->getNumber()?> <?php endif ?>",
                         "size" : "<?php if($currentCompany) :?> <?=$currentCompany->getSize()?> <?php endif ?>",
                         "restApiUrl" : "<?= $block->getRestApiUrl() ?>",
                         "template" : "Devall_Company/details"
                    }
                }
            }
        }
    }
}
</script>

